version: 2.1

workflows:
  unit-test:
    jobs:
      - setup-and-test:
          py_ver: "3.6"
          codecov_py_ver: "36"
      - setup-and-test:
          py_ver: "3.7"
          codecov_py_ver: "37"

jobs:
  setup-and-test:
    parameters:
      py_ver:
        type: string
      codecov_py_ver:
        type: string
    executor:
      name: python
      py_ver: "<< parameters.py_ver >>"
    steps:
      - checkout
      - run:
          command: python -m venv venv
      - run:
          command: ./venv/bin/python -m pip install -U setuptools pip
      - run:
          command: ./venv/bin/python -m pip install -e ".[test,packaging]"
      - run:
          command: >-
            ./venv/bin/python -m pytest
            --junitxml=test-reports/junit.xml
            --cov=./ex4mple --cov-report=xml:cov-<< parameters.py_ver >>.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
      - codecov/upload:
          file: "./cov-<< parameters.py_ver >>.xml"
          flags: "python<< parameters.codecov_py_ver >>"

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  python:
    parameters:
      py_ver:
        type: string
    docker:
      - image: "circleci/python:<< parameters.py_ver >>"
